# Generated by Django 4.2 on 2023-05-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocate',
            name='finish_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='allocate',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
