# Generated by Django 4.2.1 on 2023-05-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='is_reserved',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='equipement',
            name='is_reserved',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_reserved',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='reservedequip',
            name='is_reserved',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_reserved',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
