# Generated by Django 4.2 on 2023-05-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptrequest',
            name='message1',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='acceptrequest',
            name='message2',
            field=models.TextField(default='', editable=False),
        ),
    ]
