# Generated by Django 4.2.1 on 2023-05-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmanager',
            name='reciever',
            field=models.CharField(default='', editable=False, max_length=250),
        ),
    ]
