# Generated by Django 4.2 on 2023-04-28 01:59

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='affectation',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipement', to_field='reference', validators=[core.models.validate_reference]),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='reference',
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('reference', models.CharField(editable=False, max_length=7, unique=True)),
                ('num_serie', models.CharField(editable=False, max_length=6, unique=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('meduim', 'Meduim'), ('poor', 'Poor'), ('in_repair', 'In_repair'), ('stolen', 'Stolen'), ('reserve', 'Reserve')], default='new', max_length=255)),
                ('facture_number', models.IntegerField()),
                ('date_purchase', models.DateField(default=None)),
                ('date_assignment', models.DateField(blank=True, null=True)),
                ('discription', models.TextField(default='')),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location', to_field='name')),
                ('categorie', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.categorie_equipement', to_field='name')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
