# Generated by Django 4.2 on 2023-05-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='Id_admin',
        ),
    ]
