# Generated by Django 4.2.1 on 2023-05-15 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_allocation_is_reserved_equipement_is_reserved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie_equipement',
            name='Id_admin',
        ),
    ]
