# Generated by Django 4.2 on 2023-05-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_allocate_finish_date_alter_allocate_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocate',
            name='finish_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='allocate',
            name='start_date',
            field=models.DateField(),
        ),
    ]
