# Generated by Django 4.2.1 on 2023-05-21 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificationmanager_reciever'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocateequipements',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('panding', 'Panding')], default='panding', max_length=250),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='Location',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.location', to_field='name'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='brand',
            field=models.CharField(editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='categorie',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.categorie_equipement', to_field='name'),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('meduim', 'Meduim'), ('poor', 'Poor'), ('in_repair', 'In_repair'), ('stolen', 'Stolen'), ('reserve', 'Reserve')], default='new', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='date_purchase',
            field=models.DateField(default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='facture_number',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='model',
            field=models.CharField(editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='name',
            field=models.CharField(editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='num_serie',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location', to_field='name'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='num_serie',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
