# Generated by Django 4.2 on 2023-04-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipement_id_alter_affectation_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='date_assignment',
            field=models.DateTimeField(auto_now_add=True, default='2023-04-28 10:00:00'),
            preserve_default=False,
        ),
    ]
