# Generated by Django 4.2 on 2023-04-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_affectation_date_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='opperation',
            field=models.TextField(editable=False, max_length=255),
        ),
    ]
