# Generated by Django 4.2.1 on 2023-05-21 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_allocateequipements_status_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptallocationrequest',
            name='Allocation_request',
        ),
        migrations.AddField(
            model_name='acceptallocationrequest',
            name='request',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.allocateequipements'),
        ),
        migrations.DeleteModel(
            name='Accept',
        ),
    ]
