# Generated by Django 4.2 on 2023-04-28 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_affectation_opperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipement'),
        ),
    ]
