# Generated by Django 4.2.1 on 2023-06-08 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inventory_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, upload_to='qr_codes/'),
        ),
        migrations.CreateModel(
            name='ReturnEquipementhpc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.ForeignKey(limit_choices_to={'Location__type': 'it_room', 'is_reserved': True}, on_delete=django.db.models.deletion.CASCADE, to='core.inventory', to_field='reference')),
            ],
        ),
    ]
