# Generated by Django 4.2.1 on 2023-06-09 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_stock_qr_code_returnequipementhpc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertRequestedEq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.ForeignKey(limit_choices_to={'Location__type': 'it_room', 'is_requested': True, 'is_reserved': False}, on_delete=django.db.models.deletion.CASCADE, to='core.inventory', to_field='reference')),
            ],
        ),
    ]
