# Generated by Django 4.2 on 2023-04-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_affectation_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='reference',
            field=models.CharField(editable=False, max_length=7),
        ),
        migrations.AlterField(
            model_name='stock',
            name='reference',
            field=models.CharField(editable=False, max_length=7),
        ),
    ]
