# Generated by Django 4.2 on 2023-04-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_equipement_reference_alter_stock_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='reference',
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='reference',
            field=models.CharField(editable=False, max_length=7, unique=True),
        ),
    ]
