# Generated by Django 4.2.1 on 2023-05-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_acceptallocationrequest_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocateequipements',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('panding', 'Panding'), ('refuse', 'Resfuse')], default='panding', editable=False, max_length=250),
        ),
    ]
