# Generated by Django 4.2 on 2023-04-29 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_equipement_reference_alter_stock_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='reference',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Location',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.location', to_field='name'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='brand',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='categorie',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.categorie_equipement', to_field='name'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('meduim', 'Meduim'), ('poor', 'Poor'), ('in_repair', 'In_repair'), ('stolen', 'Stolen'), ('reserve', 'Reserve')], max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_assignment',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date_purchase',
            field=models.DateField(default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='facture_number',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='model',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
