# Generated by Django 4.2.1 on 2023-05-23 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_allocateequipements_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='is_requested',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='is_requested',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_requested',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='acceptallocationrequest',
            name='request',
            field=models.ForeignKey(limit_choices_to={'status': 'Panding'}, on_delete=django.db.models.deletion.CASCADE, to='core.allocateequipements'),
        ),
        migrations.AlterField(
            model_name='allocateequipements',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('panding', 'Panding'), ('refuse', 'Refuse')], default='panding', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='num_serie',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
