# Generated by Django 4.2 on 2023-04-29 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_stock_reference_alter_inventory_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=255)),
                ('brand', models.CharField(editable=False, max_length=255)),
                ('model', models.CharField(editable=False, max_length=255)),
                ('reference', models.CharField(editable=False, max_length=7, unique=True)),
                ('num_serie', models.CharField(editable=False, max_length=6, unique=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('meduim', 'Meduim'), ('poor', 'Poor'), ('in_repair', 'In_repair'), ('stolen', 'Stolen'), ('reserve', 'Reserve')], max_length=255)),
                ('facture_number', models.IntegerField(editable=False)),
                ('date_purchase', models.DateField(default=None, editable=False)),
                ('date_assignment', models.DateField(blank=True, editable=False, null=True)),
                ('discription', models.TextField(default='')),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('Location', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.location', to_field='name')),
                ('categorie', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.categorie_equipement', to_field='name')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
