# Generated by Django 4.2.1 on 2023-05-23 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_equipement_is_requested_inventory_is_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocateequipements',
            name='reference',
            field=models.ForeignKey(limit_choices_to={'Location__type': 'reservation_room', 'is_requested': False, 'is_reserved': False}, on_delete=django.db.models.deletion.CASCADE, to='core.inventory', to_field='reference'),
        ),
    ]
