# Generated by Django 4.2.1 on 2023-05-23 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_allocateequipements_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.ForeignKey(limit_choices_to={'Location__type': 'reservation_room', 'is_requested': True, 'is_reserved': True}, on_delete=django.db.models.deletion.CASCADE, to='core.inventory', to_field='reference')),
            ],
        ),
    ]
